[versions]
minecraft = "1.3.1"
feather_build = "28"
nests_build = "4"
#raven_build = "1"
#sparrow_build = "1"
fabric_loader = "0.16.9"
loom = "1.8-SNAPSHOT"
ploceus = "1.8-SNAPSHOT"
vineflower = "1.10.1"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
ploceus = { id = "ploceus", version.ref = "ploceus" }
